# move card from "in progress" to "todo" if it has no assignee
on:
    issues:
        types: [ unassigned ]

jobs:
    check_and_label:
        name: Move card to todo on unassignment
        runs-on: ubuntu-latest
        steps:
            -   uses: actions/github-script@v3
                with:
                    github-token: ${{secrets.GITHUB_TOKEN}}
                    script: |
                        const issue = context.payload.issue;
                        const issue_url = issue.url;
                        const issue_assignees = issue.assignees;

                        const todo_column_id = 15663135;
                        const doing_column_id = 15663136;

                        const help_wanted_label_mark = 'help wanted';
                        const todo_label_mark = 'confirmed'
                        const in_progress_label_mark = 'in progress';

                        // fetch all cards in doing

                        const hasNoAssignees = (!issue_assignees) || (issue_assignees && issue_assignees.length === 0)

                        if( hasNoAssignees){
                            const res = await github.projects.listCards({
                              column_id: doing_column_id
                            })
                            const doing_cards = res.data

                            const find = (arr, f) => {
                                if(!arr){
                                    return null;
                                }
                                const filteredValue = arr.filter(x => f(x))
                                if( filteredValue && filteredValue.length > 0){
                                    return filteredValue[0]
                                }
                                return null;
                            }

                            if(doing_cards){
                                console.log('got column');
                                console.log(doing_cards);

                                //then filter by content_url
                                const card_matching_issue = find(doing_cards, card => (card['content_url'] === issue_url));

                                // if match, move it to todo column
                                if (card_matching_issue){
                                  console.log('matching');
                                  const card_id = card_matching_issue.id;

                                  github.projects.moveCard({
                                    card_id: card_id,
                                    position: 'top',
                                    column_id: todo_column_id
                                  });

                                  github.issues.removeLabel({
                                      owner: context.repo.owner,
                                      repo: context.repo.repo,
                                      issue_number: context.payload.issue.number,
                                      name: in_progress_label_mark,
                                  });

                                  github.issues.addLabels({
                                      owner: context.repo.owner,
                                      repo: context.repo.repo,
                                      issue_number: context.payload.issue.number,
                                      labels: [help_wanted_label_mark, todo_label_mark],
                                  });
                                }
                            }else{
                                console.log('not found')
                            }
                        }
